auth:
    algorithm: <algorithm>
    secret_key: <secret>

redcap:
    api_url: <url>
    api_token: <token>

fhir:
    profiles:
        <resource>:
            - <canonical url>
    system_uri: <system uri>
